name: Build and deploy Node.js app to Azure Web App - FrontReact

on:
  push:
    branches:
      - master  # O la rama que estés usando para producción
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist  # Cambié esto para solo comprimir dist/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F305582472D409681B2C913F38B6C2D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_84A1ED1553B0469BB15D78E706D13EEC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F1537AE2737E4431B3DDE027E387DF82 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FrontReact'  # Nombre de la aplicación en Azure
          slot-name: 'Production'
          package: release.zip  # Aquí usamos el archivo zip, no la carpeta dist
